language: node_js
node_js:
  - "8"
  - "11"
cache:
  yarn: true
  directories:
    - node_modules
branches:
  only:
    - master
install:
  - yarn install
script:
  - yarn lint
  - yarn test
after_success:
  - yarn codecov
