version: 2.1

executors:
  node:
    parameters:
      browsers:
        type: boolean
        default: false
    docker:
      - image: circleci/node:latest<<# parameters.browsers >>-browsers<</ parameters.browsers >>
    working_directory: ~/project
    environment:
      NODE_ENV: test

commands: 
  attach-project:
    steps:
      - checkout
      - attach_workspace:
          at: ~/project

release_branches_only: &release_branches_only
  filters:
    branches:
      only:
        - master
        - next

jobs:
  has-commits:
    executor: node
    steps:
      - checkout
      - run:
          name: Have there been new commits
          command: |
            [ $(git log --since=23.hours --pretty=oneline | wc -l) -gt 0 ]

  setup:
    executor: node
    steps:
      - checkout
      - restore_cache:
          key: yarn-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: NODE_ENV=dev yarn
      - save_cache:
          key: yarn-{{ checksum "yarn.lock" }}
          paths:
            - "node_modules"
      - persist_to_workspace:
          root: ~/project
          paths:
            - node_modules

  lint:
    executor: node
    steps:
      - attach-project
      - run:
          name: Lint
          command: yarn lint

  audit:
    executor: node
    steps:
      - attach-project
      - run:
          name: Security Audit
          command: yarn audit

  test-unit:
    executor: node
    steps:
      - attach-project
      - run:
          name: Unit Tests
          command: yarn test:unit --coverage && yarn coverage

  test-e2e-ssr:
    executor: node
    steps:
      - attach-project
      - run:
          name: E2E SSR Tests
          command: yarn test:e2e-ssr
      - persist_to_workspace:
          root: ~/project
          paths:
            - test/fixtures

  test-e2e-browser:
    parameters:
      browserString:
        type: string
    executor:
      name: node
      browsers: true
    steps:
      - attach-project
      - run:
          name: E2E Browser Tests
          command: yarn test:e2e-browser
          environment:
            BROWSER_STRING: << parameters.browserString >>

  release:
    parameters:
      nightly:
        type: boolean
        default: false
    executor: node
    steps:
      - attach-project
      - run:
          name: release
          command: |
            ONLY_ON="[release]"
            NIGHTLY="<<# parameters.nightly >>1<</ parameters.nightly >>"
            COMMIT_MSG=${COMMIT_MSG:-`git --no-pager log --pretty=full -n1 $CIRCLE_SHA1`}
            if [ "$NIGHTLY" = "1" ] || [[ "$COMMIT_MSG" == *"$ONLY_ON"* ]]; then
              echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
              echo "//registry.yarnpkg.com/:_authToken=$NPM_TOKEN" >> ~/.npmrc
              RELEASE_TYPE=${CIRCLE_BRANCH/master/edge}
              if [ "$RELEASE_TYPE" = "next" ]; then release="--release major"; fi
              # Set next package version
              yarn standard-version --skip.changelog true --skip.tag true --skip.commit true $release
              # Retrieve next package version
              CURVER=`jq -r .version package.json | sed 's/-.*//'`
              # Create custom prerelease version string
              PREVER="$(($(date +%s) / 60)).$(git rev-parse --short HEAD)"
              # Set version string to include custom prerelease
              echo "$(jq '.version = "'$CURVER'-'$PREVER'"' package.json)" > package.json
              # Build
              yarn build
              # Publish
              npm publish --dry-run -q --tag $RELEASE_TYPE
            else
              echo "Release phase was skipped."
            fi

workflows:
  version : 2

  commit:
    jobs:
      - setup
      - lint:             { requires: [setup] }
      - audit:            { requires: [setup] }
      - test-unit:        { requires: [lint] }
      - test-e2e-ssr:     { requires: [lint] }
      - test-e2e-browser:
          name:           test-e2e-firefox
          browserString:  firefox/headless
          requires:       [test-e2e-ssr]
      - test-e2e-browser:
          name:           test-e2e-chrome
          browserString:  chrome/selenium
          requires:       [test-e2e-ssr]
      - test-e2e-browser:
          name:           test-e2e-ie
          browserString:  browserstack/local/windows 7/ie:9
          requires:       [test-e2e-ssr]
          <<: *release_branches_only
      - test-e2e-browser:
          name:           test-e2e-edge
          browserString:  browserstack/local/edge:15
          requires:       [test-e2e-ssr]
          <<: *release_branches_only
      - test-e2e-browser:
          name:           test-e2e-safari
          browserString:  browserstack/local/os x=snow leopard/safari:5.1
          requires:       [test-e2e-ssr]
          <<: *release_branches_only
      - release:
          name: manual release
          # requires: [setup, lint, audit, test-unit, test-e2e-ssr, test-e2e-firefox, test-e2e-chrome, test-e2e-ie, test-e2e-edge, test-e2e-safari]
          requires: [setup, lint, test-unit, test-e2e-ssr, test-e2e-firefox, test-e2e-chrome]
          <<: *release_branches_only

  nightly:
    jobs:
      - has-commits
      - setup:            { requires: [has-commits] }
      - lint:             { requires: [setup] }
      - audit:            { requires: [setup] }
      - test-unit:        { requires: [lint] }
      - test-e2e-ssr:     { requires: [lint] }
      - test-e2e-browser:
          name:           test-e2e-firefox
          browserString:  firefox/headless
          requires:       [test-e2e-ssr]
      - test-e2e-browser:
          name:           test-e2e-chrome
          browserString:  chrome/selenium
          requires:       [test-e2e-ssr]
      - test-e2e-browser:
          name:           test-e2e-ie
          browserString:  browserstack/local/windows 7/ie:9
          requires:       [test-e2e-ssr]
      - test-e2e-browser:
          name:           test-e2e-edge
          browserString:  browserstack/local/edge:15
          requires:       [test-e2e-ssr]
      - test-e2e-browser:
          name:           test-e2e-safari
          browserString:  browserstack/local/os x=snow leopard/safari:5.1
          requires:       [test-e2e-ssr]
      - release:
          nightly: true
          name: nightly release
          requires: [setup, lint, audit, test-unit, test-e2e-ssr, test-e2e-firefox, test-e2e-chrome, test-e2e-ie, test-e2e-edge, test-e2e-safari]
    triggers:
      - schedule:
          cron: "0 0 * * *"
          <<: *release_branches_only
